---

    - name: restart webapp
      supervisorctl:
        name: "{{ service_name }}"
        state: restarted

    - name: pull version of updated service | fail for version before v1.1.0!
      become: no
      local_action: command curl {{ enable_ssl | ternary('https', 'http') }}://{{ webserver_dns }}/version/
      register: result

    - set_fact:
        installed_service_version: "{{ result.stdout | from_json }}"

    - debug:
        msg: "installed version {{ installed_service_version.version }} -- {{ result.stdout }}"

    - name: check that it is correct
      fail:
          msg: expected {{ service_git_revision }} got {{ installed_service_version.version }}
      when: service_git_revision != installed_service_version.version
