---
- hosts: '{{ target_hosts | default("tag_webserver", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/common_vars.yml
      - vars/catchpy_vars.yml

  tasks:
      - name: install python2
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        register: result
        changed_when: "result.stdout != ''"


- hosts: '{{ target_hosts | default("tag_webserver", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      local_user:
          name: '{{ service_name }}'
          authorized: []
  vars_files:
    - vars/common_vars.yml
    - vars/catchpy_vars.yml

  tasks:
      - name: passwordless sudo
        include_role:
            name: external/jmcvetta.passwordless_sudo

      - name: install packages
        include_role:
            name: external/nmaekawa.apt
        vars:
            apt_other_packages: '{{ apt_required_packages_catchpy }}'

      - name: create devo, service users
        include_role:
            name: external/Stouts.users
        vars:
            users_users: '{{ users_developers + [local_user] }}'


- hosts: '{{ target_hosts | default("tag_webserver", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
    - vars/common_vars.yml
    - vars/catchpy_vars.yml

  handlers:
    - include: handlers/handlers.yml

  tasks:
      - name: setup webserver name
        include_tasks: 'roles/facts_setup/tasks/webserver_dns.yml'

      - name: install webapp
        include_role:
            name: webapp

      - name: run migration and collectstatic
        include_tasks: 'roles/webapp/tasks/django_manage.yml'

      - name: create django admin user
        include_tasks: 'roles/webapp/tasks/django_admin_user.yml'

      - name: config nginx
        include_role:
            name: nginx
        vars:
            nginx_template_path: roles/nginx/templates/nginx_catchpy.j2





