---
    #
    # nmaekawa.cloudwatch is a dependency role
    #
    # `cloudwatch_user_home` is setup in nmaekawa.cloudwatch/tasks/set_instance_facts.yml
    # `custom_metrics_shared.sh` is assumed to be in `cloudwatch_user_home`/bin
    #

    - name: copy response_time scripts
      template:
        src: "{{ item }}"
        dest: "{{ cloudwatch_user_home }}/bin/{{ item | basename }}"
        owner: "{{ cloudwatch_user }}"
        group: "{{ cloudwatch_user }}"
        mode: "0775"
      with_fileglob:
        - "../templates/*response_time*.sh"
      when: "'tag_webserver' in group_names or 'tag_webserver_candidate' in group_names"

    - name: copy make_jwt script
      template:
        src: "../templates/make_jwt.py"
        dest: "{{ cloudwatch_user_home }}/bin/make_jwt.py"
        owner: "{{ cloudwatch_user }}"
        group: "{{ cloudwatch_user }}"
        mode: "0775"
      when: "'tag_webserver' in group_names or 'tag_webserver_candidate' in group_names"



