---
    #
    # nmaekawa.cloudwatch is a dependency role
    #
    # `cloudwatch_user_home` is setup in nmaekawa.cloudwatch/tasks/set_instance_facts.yml
    #

    - name: ensure tmp folder exists
      file:
        path: "{{ cloudwatch_user_home }}/tmp/cloudwatch"
        owner: "root"
        group: "root"
        mode: 0755
        state: directory

