---
    - include_tasks: create_dirs.yml
    - include_tasks: copy_metric_scripts.yml
    - include_tasks: create_cloudwatch_consumer.yml
      when: "'tag_webserver' in groupnames or 'tag_webserver_candidate' in group_names"
    - include_tasks: set_cronjobs.yml

