---
    #
    # nmaekawa.cloudwatch is a dependency role
    # `cloudwatch_user_home` is setup in 
    # nmaekawa.cloudwatch/tasks/set_instance_facts.yml
    #

    - name: set cronjob for webapp availability
      cron:
        name: "{{ service_name }}_availability"
        user: "cloudwatch"
        minute: "*/5"
        state: present
        job: >
            {{ cloudwatch_user_home }}/bin/{{ service_name }}_response_time_metric.sh 2>&1 | logger -t info
      when: "'tag_webserver' in group_names or 'tag_webserver_candidate' in group_names"
